---
title: "Incidence"
author: "Jurrian van de Kraats"
date: "`r Sys.Date()`"
output: html_document
---

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
#install.packages('data.table')
library(knitr)
library(data.table)
library(tidyverse)
library(readxl)
library(lubridate)
```


```{r}

# load the tables
O_P <- read.csv("Tables/OBSERVATION_PERIODS.csv")
events <- read.csv('Tables/EVENTS.csv')
persons <- read.csv('Tables/PERSONS.csv')
instance <- read.csv('Tables/INSTANCE.csv')
codelist <- read_excel("Tables/CodeList_20210128(1).xlsx", 
    sheet = "ANAPHYL")
codelist2 <- read_excel("Tables/CodeList_20210128(1).xlsx", 
    sheet = "GBS")
```

### Step 1


```{r}


dfp1 <- O_P %>% 
  filter(op_start_date <= 20160101, # Remove individuals that do not have at least 1 year of FU before start of study
         op_end_date >= 20170102) # make sure that the individuals at least have 1 day of fu during study period 
dfp1$start_study <- 20170101
```

```{r}
# Make sure that all dates are in Date format YYYY-MM-DD
dfp1 <- dfp1 %>% 
  mutate(op_start_date = as.Date(ymd(op_start_date)),
         op_end_date = as.Date(ymd(op_end_date)),
         start_study = as.Date(ymd(start_study)))
```


### Step 2

```{r}
persons <- persons %>% 
  mutate(birthdate = as.Date(ymd(year_of_birth*10000+month_of_birth*100+day_of_birth)), # calculate the birth date
         age = as.numeric(difftime
                          (as.Date(ymd(20170101)), 
                            birthdate, units='days')) / 365.25, # calculate the age 
         age_bands = cut(age, breaks = c(0,19,39,59,79,Inf), 
                         include.lowest = T,include.highest = T, 
                         labels = c("[0,19]",'[20,39]', '[40,59]', '[60,79]', '[80+]')) # Make sure the ages are divided in age bands 
                         ) %>% 
  filter(age >= 0)
```



### Step 3

```{r}
data <- left_join(dfp1, persons, by = "person_id") # merge the OBSERVATION_PERIODS and PERSONS table (keep only individuals who are in OBSERVATIONS_PERIODS table)
```

### Step 4

```{r}
anaphyl <- codelist %>% 
  filter(`Coding system`== c('ICD9', 'ICD10/CM'))

gbs <- codelist2 %>% 
  filter(`Coding system`== c('ICD9', 'ICD10/CM'))

codes <- data.table(Diagnosis = paste0('anaphyl_',anaphyl$Algorithm,sep = ""), 
                event_code = anaphyl$Code, 
                vocabulary = anaphyl$`Coding system`)

gbstemp <- data.table(Diagnosis = paste0('gbs_',gbs$Algorithm,sep = ""), 
                event_code = gbs$Code, 
                vocabulary = gbs$`Coding system`)

codes <- rbind(codes, gbstemp)

kable(codes) ## Deze op later moment nog wat mooier maken 

```


### Step 5

```{r}
dfp2 <- merge(codes, events, by = 'event_code')
dfp2 <- dfp2 %>% 
  filter(start_date_record > 20170101,
         start_date_record < 20210101) %>% 
  arrange(start_date_record)

dfp2 <- dfp2[!duplicated(dfp2$person_id)]
dfp2$end_date_record <- dfp2$start_date_record
dfp2$is_event <- 1

```

```{r}
dftotal <- left_join(data,dfp2, by = 'person_id')
dftotal$is_event[is.na(dftotal$is_event)] <- 0
```

```{r}
# einde van de studie periode op het moment dat er een event is bij een observatie
dftotal$end_incidence <- as.Date(ymd(dftotal$end_date_record))
# When observation does not have an event, make sure end_incidence is coded as end study period (2021-01-01)
dftotal$end_incidence[is.na(dftotal$end_incidence)] <- as.Date(ymd(20210101)) 
#Calculate how many years each observaiton was in the study. 
dftotal$years_in_study <- as.numeric(difftime
                          (dftotal$end_incidence, 
                            dftotal$start_study, units='days')) / 365.25

```


```{r}
#total PY in study period
TPY <- sum(dftotal$years_in_study)

#calculate the amount of anaph shocks Possible in study period 
TNE_anaphP <- dftotal %>% 
  filter(Diagnosis == 'anaphyl_possible') %>% nrow()

# Incidence Rate for anaph shock possible in study period 
(iro_anaphP <- TNE_anaphP/TPY * 1000)

#calculate the amount of anaph shocks narrow in study period 
TNE_anaphN <- dftotal %>% 
  filter(Diagnosis == 'anaphyl_narrow') %>% nrow()

# IR for anaph shock narrow in study period
(iro_anaphN <- TNE_anaphN/TPY * 1000)

# amount of gbs cases in study period
TNE_gbs <- dftotal %>% 
  filter(Diagnosis == 'gbs_narrow') %>% nrow()

# IR for gbs in study period
(iro_gbs <- TNE_gbs/TPY * 1000)
```


---------------------------

2017!!! 

```{r}
# Add for every observations with an event the date of the event in the dataset. 
dftotal$end_incidence_2017 <- as.Date(ymd(dftotal$end_date_record)) 
# for every observtion who does not have an event, make sure these will get the start of 2018 as end date, since we want to calculate the IR for 2017
dftotal$end_incidence_2017[is.na(dftotal$end_incidence_2017)] <- as.Date(ymd(20180101))

# If observation has an event after 2017, it will become the end of the obs period (2018-01-01)
dftotal$end_incidence_2017 <- as.Date(ifelse(year(dftotal$end_incidence_2017) > 2017, as.Date("2018-01-01"), dftotal$end_incidence_2017), origin = "1970-01-01")
```



```{r}
# Make end incidence for every year
df_2018 <- 
  dftotal %>% 
  filter(!year(end_incidence) == 2017)

df_2019 <- 
  df_2018 %>% 
  filter(!year(end_incidence) == 2018)

df_2020 <- 
  df_2019 %>% 
  filter(!year(end_incidence) == 2019)

df_2021 <- 
  df_2020 %>% 
  filter(!year(end_incidence) == 2020) 



```



```{r}
# calculate for each individual the py observed in 2017. 
dftotal$years_in_study_2017 <- as.numeric(difftime
                          (dftotal$end_incidence_2017, 
                            dftotal$start_study, units='days')) / 365
```


```{r}
# Calculate the events in 2017
events_2017 <- subset(dftotal, year(end_incidence) == 2017) 

#the Total personyears for an event in 2017
TPY_2017 <- sum(dftotal$years_in_study_2017)

# Count the amount of anaphyl possible shocks in 2017 
TNE_anaphP_2017 <- events_2017 %>% 
  filter(Diagnosis == 'anaphyl_possible') %>% nrow()

# calculate the IR in 1000 PY for anaphyl possible in 2017
(iro_anaphP_2017_1000PY <- TNE_anaphP_2017/TPY_2017 * 1000)


# Count the amount of anaphyl shocks narrow in 2017 
TNE_anaphN_2017 <- events_2017 %>% 
  filter(Diagnosis == 'anaphyl_narrow') %>% nrow()

# calculate the IR in 1000 PY for anaphyl narrow in 2017
(iro_anaphN_2017_1000PY <- TNE_anaphN_2017/TPY_2017 * 1000)

# Count the amount of gbs in 2017 
TNE_gbs_2017 <- events_2017 %>% 
  filter(Diagnosis == 'gbs_narrow') %>% nrow()

# calculate the IR in 1000 PY for gbs in 2017
(iro_gbs_2017_1000PY <- TNE_gbs_2017/TPY_2017*1000)
```


2018
```{r}
# for every observation who has an event put in the date. 
df_2018$end_incidence_2018 <- as.Date(ymd(df_2018$end_date_record))

#for everybody who does not have an event, make sure the end of incidence is 01-01-2019. 
df_2018$end_incidence_2018[is.na(df_2018$end_incidence_2018)] <- as.Date(ymd(20190101))

# If an observation has the event after 2018, the end of the observation will be 01-01-2019
df_2018$end_incidence_2018 <- as.Date(ifelse(year(df_2018$end_incidence_2018) > 2018, as.Date("2019-01-01"), df_2018$end_incidence_2018), origin = "1970-01-01")
df_2018$start_incidence_2018 <- as.Date(ymd(20180101))

# Count the person years of the observation in 2018
df_2018$years_in_study_2018 <- as.numeric(difftime
                          (df_2018$end_incidence_2018, 
                            df_2018$start_incidence_2018, units='days')) / 365

```


```{r}

# All the events in 2018 in a new dataset
events_2018 <- subset(dftotal, year(end_incidence) == 2018) 

# Total person years observed in 2018
TPY_2018 <- sum(df_2018$years_in_study_2018)

# Amount of events of anaphylatic shock possible in 2018 
TNE_anaphP_2018 <- events_2018 %>% 
  filter(Diagnosis == 'anaphyl_possible') %>% nrow()

# Incidence rate in 1000 PY for anaphalytic shock possible in 2018
(iro_anaphP_2018_1000PY <- TNE_anaphP_2018/TPY_2018 * 1000)


# Amount of events of anaphylatic shock narrow in 2018 
TNE_anaphN_2018 <- events_2018 %>% 
  filter(Diagnosis == 'anaphyl_narrow') %>% nrow()

# IR in 1000 PY for anaphalytic shock naroow in 2018
(iro_anaphN_2018_1000PY <- TNE_anaphN_2018/TPY_2018 * 1000)


# Amount of events of GBS in 2018 
TNE_gbs_2018 <- events_2018 %>% 
  filter(Diagnosis == 'gbs_narrow') %>% nrow()

#IR for gbs in 1000 PY
(iro_gbs_2018_1000PY <- TNE_gbs_2018/TPY_2018*1000)
```

2019

```{r}
# for every observation who has an event put in the date. 
df_2019$end_incidence_2019 <- as.Date(ymd(df_2019$end_date_record))

#for everybody who does not have an event, make sure the end of incidence is 01-01-2019. 
df_2019$end_incidence_2019[is.na(df_2019$end_incidence_2019)] <- as.Date(ymd(20200101))

# If an observation has the event after 2018, the end of the observation will be 01-01-2019
df_2019$end_incidence_2019 <- as.Date(ifelse(year(df_2019$end_incidence_2019) > 2019, as.Date("2020-01-01"), df_2019$end_incidence_2019), origin = "1970-01-01")
df_2019$start_incidence_2019 <- as.Date(ymd(20190101))

# Count the person years of the observation in 2018
df_2019$years_in_study_2019 <- as.numeric(difftime
                          (df_2019$end_incidence_2019, 
                            df_2019$start_incidence_2019, units='days')) / 365

```


```{r}

# All the events in 2019 in a new dataset
events_2019 <- subset(dftotal, year(end_incidence) == 2019) 

# Total person years observed in 2019
TPY_2019 <- sum(df_2019$years_in_study_2019)

# Amount of events of anaphylatic shock possible in 2019 
TNE_anaphP_2019 <- events_2019 %>% 
  filter(Diagnosis == 'anaphyl_possible') %>% nrow()

# Incidence rate in 1000 PY for anaphalytic shock possible in 2019
(iro_anaphP_2019_1000PY <- TNE_anaphP_2019/TPY_2019 * 1000)


# Amount of events of anaphylatic shock narrow in 2019 
TNE_anaphN_2019 <- events_2019 %>% 
  filter(Diagnosis == 'anaphyl_narrow') %>% nrow()

# IR in 1000 PY for anaphalytic shock naroow in 2019
(iro_anaphN_2019_1000PY <- TNE_anaphN_2019/TPY_2019 * 1000)


# Amount of events of GBS in 2019 
TNE_gbs_2019 <- events_2019 %>% 
  filter(Diagnosis == 'gbs_narrow') %>% nrow()

#IR for gbs in 1000 PY
(iro_gbs_2019_1000PY <- TNE_gbs_2019/TPY_2019*1000)
```


2020
```{r}
# for every observation who has an event put in the date. 
df_2020$end_incidence_2020 <- as.Date(ymd(df_2020$end_date_record))

#for everybody who does not have an event, make sure the end of incidence is 01-01-2021. 
df_2020$end_incidence_2020[is.na(df_2020$end_incidence_2020)] <- as.Date(ymd(20210101))

# If an observation has the event after 2018, the end of the observation will be 01-01-2020
df_2020$end_incidence_2020 <- as.Date(ifelse(year(df_2020$end_incidence_2020) > 2020, as.Date("2021-01-01"), df_2020$end_incidence_2020), origin = "1970-01-01")
df_2020$start_incidence_2020 <- as.Date(ymd(20200101))

# Count the person years of the observation in 2018
df_2020$years_in_study_2020 <- as.numeric(difftime
                          (df_2020$end_incidence_2020, 
                            df_2020$start_incidence_2020, units='days')) / 365

```


```{r}

# All the events in 2020 in a new dataset
events_2020 <- subset(dftotal, year(end_incidence) == 2020) 

# Total person years observed in 2020
TPY_2020 <- sum(df_2020$years_in_study_2020)

# Amount of events of anaphylatic shock possible in 2020 
TNE_anaphP_2020 <- events_2020 %>% 
  filter(Diagnosis == 'anaphyl_possible') %>% nrow()

# Incidence rate in 1000 PY for anaphalytic shock possible in 2020
(iro_anaphP_2020_1000PY <- TNE_anaphP_2020/TPY_2020 * 1000)


# Amount of events of anaphylatic shock narrow in 2020 
TNE_anaphN_2020 <- events_2020 %>% 
  filter(Diagnosis == 'anaphyl_narrow') %>% nrow()

# IR in 1000 PY for anaphalytic shock naroow in 2020
(iro_anaphN_2020_1000PY <- TNE_anaphN_2020/TPY_2020 * 1000)


# Amount of events of GBS in 2020 
TNE_gbs_2020 <- events_2020 %>% 
  filter(Diagnosis == 'gbs_narrow') %>% nrow()

#IR for gbs in 1000 PY
(iro_gbs_2020_1000PY <- TNE_gbs_2020/TPY_2020*1000)
```


```{r}
Diagnosis <- c('anaphylaxis_narrow', 'anaphylaxis_narrow', 'anaphylaxis_narrow', 'anaphylaxis_narrow','anaphylaxis_narrow', 'anaphylaxis_possible', 'anaphylaxis_possible', 'anaphylaxis_possible', 'anaphylaxis_possible', 'anaphylaxis_possible', 'gbs_narrow', 'gbs_narrow', 'gbs_narrow', 'gbs_narrow', 'gbs_narrow')
Years <- c('Total', '2017', '2018', '2019', '2020',
           'Total', '2017', '2018', '2019', '2020',
           'Total', '2017', '2018', '2019', '2020')

IR <- round(c(iro_anaphN, iro_anaphN_2017_1000PY, iro_anaphN_2018_1000PY, iro_anaphN_2019_1000PY, iro_anaphN_2020_1000PY, iro_anaphP,
        iro_anaphP_2017_1000PY, iro_anaphP_2018_1000PY, iro_anaphP_2019_1000PY, iro_anaphP_2020_1000PY, iro_gbs, iro_gbs_2017_1000PY, iro_gbs_2018_1000PY, iro_gbs_2019_1000PY, iro_gbs_2020_1000PY),2)


tab <- data.frame(Diagnosis = Diagnosis, Year = Years, 'IR per 1000 py' = IR)
tab
```


```{r}

make_year_age_bands <- function(data, age_group) {
  new_data <- data %>% 
    filter(age_bands==age_group) 
  return(new_data)
  }


dftotal0019 <- make_year_age_bands(dftotal, '[0,19]')
dftotal2039 <- make_year_age_bands(dftotal, '[20,39]')
dftotal4059 <- make_year_age_bands(dftotal, '[40,59]')
dftotal6079 <- make_year_age_bands(dftotal, '[60,79]')
dftotal80 <- make_year_age_bands(dftotal, '[80+]')

```


```{r}
# Make function to calculate amount of events
amount_events <- function(data, diagn) {
  events <- data %>% 
    filter(Diagnosis == diagn) %>%  nrow()
  return(events)
}
```


```{r}
#total personyears in study for ageband 0-19
TPY0019 <- sum(dftotal0019$years_in_study)
# amount of events for each event for age_band 0-19
TNE_anaphP0019 <- amount_events(dftotal0019, 'anaphyl_possible')
TNE_anaphN0019 <- amount_events(dftotal0019, 'anaphyl_narrow')
TNE_gbs0019 <- amount_events(dftotal0019, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP0019 <- TNE_anaphP0019/TPY0019 * 1000)
(iro_anaphN0019 <- TNE_anaphN0019/TPY0019 * 1000)
(iro_gbs0019 <- TNE_gbs0019/TPY0019 * 1000)
```

```{r}
#total personyears in study for ageband 20-39
TPY2039 <- sum(dftotal2039$years_in_study)
# amount of events for each event for age_band 20-39
TNE_anaphP2039 <- amount_events(dftotal2039, 'anaphyl_possible')
TNE_anaphN2039 <- amount_events(dftotal2039, 'anaphyl_narrow')
TNE_gbs2039 <- amount_events(dftotal2039, 'gbs_narrow')

#IR for each event in 1000PY for age_band 20-39 
(iro_anaphP2039 <- TNE_anaphP2039/TPY2039 * 1000)
(iro_anaphN2039 <- TNE_anaphN2039/TPY2039 * 1000)
(iro_gbs2039 <- TNE_gbs2039/TPY2039 * 1000)
```

```{r}
#total personyears in study for ageband 0-19
TPY4059 <- sum(dftotal4059$years_in_study)
# amount of events for each event for age_band 0-19
TNE_anaphP4059 <- amount_events(dftotal4059, 'anaphyl_possible')
TNE_anaphN4059 <- amount_events(dftotal4059, 'anaphyl_narrow')
TNE_gbs4059 <- amount_events(dftotal4059, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP4059 <- TNE_anaphP4059/TPY4059 * 1000)
(iro_anaphN4059 <- TNE_anaphN4059/TPY4059 * 1000)
(iro_gbs4059 <- TNE_gbs4059/TPY4059 * 1000)
```

```{r}
#total personyears in study for ageband 0-19
TPY6079 <- sum(dftotal6079$years_in_study)
# amount of events for each event for age_band 0-19
TNE_anaphP6079 <- amount_events(dftotal6079, 'anaphyl_possible')
TNE_anaphN6079 <- amount_events(dftotal6079, 'anaphyl_narrow')
TNE_gbs6079 <- amount_events(dftotal6079, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP6079 <- TNE_anaphP6079/TPY6079 * 1000)
(iro_anaphN6079 <- TNE_anaphN6079/TPY6079 * 1000)
(iro_gbs6079 <- TNE_gbs6079/TPY * 1000)
```


```{r}
#Events in 2017 for age group 00-19
events_2017_0019 <- subset(dftotal0019, year(end_incidence) == 2017) 
#the Total personyears for an event in 2017 age_band0019
TPY_2017_0019 <- sum(dftotal0019$years_in_study_2017)

# Count thenumber of events for age_band 0019 in 2017
TNE_anaphP_0019_2017 <- amount_events(events_2017_0019, 'anaphyl_possible')
TNE_anaphN_0019_2017 <- amount_events(events_2017_0019, 'anaphyl_narrow')
TNE_gbs_0019_2017 <- amount_events(events_2017_0019, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_0019_2017 <- TNE_anaphP_0019_2017/TPY_2017_0019 * 1000)
(iro_anaphN_0019_2017 <- TNE_anaphN_0019_2017/TPY_2017_0019 * 1000)
(iro_gbs_0019_2017 <- TNE_gbs_0019_2017/TPY_2017_0019 * 1000)
```

```{r}
#Events in 2017 for age group 00-19
events_2017_2039 <- subset(dftotal2039, year(end_incidence) == 2017) 
#the Total personyears for an event in 2017 age_band2039
TPY_2017_2039 <- sum(dftotal2039$years_in_study_2017)

# Count thenumber of events for age_band 2039 in 2017
TNE_anaphP_2039_2017 <- amount_events(events_2017_2039, 'anaphyl_possible')
TNE_anaphN_2039_2017 <- amount_events(events_2017_2039, 'anaphyl_narrow')
TNE_gbs_2039_2017 <- amount_events(events_2017_2039, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_2039_2017 <- TNE_anaphP_2039_2017/TPY_2017_2039 * 1000)
(iro_anaphN_2039_2017 <- TNE_anaphN_2039_2017/TPY_2017_2039 * 1000)
(iro_gbs_2039_2017 <- TNE_gbs_2039_2017/TPY_2017_2039 * 1000)
```

```{r}
#Events in 2017 for age group 00-19
events_2017_4059 <- subset(dftotal4059, year(end_incidence) == 2017) 
#the Total personyears for an event in 2017 age_band4059
TPY_2017_4059 <- sum(dftotal4059$years_in_study_2017)

# Count thenumber of events for age_band 4059 in 2017
TNE_anaphP_4059_2017 <- amount_events(events_2017_4059, 'anaphyl_possible')
TNE_anaphN_4059_2017 <- amount_events(events_2017_4059, 'anaphyl_narrow')
TNE_gbs_4059_2017 <- amount_events(events_2017_4059, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_4059_2017 <- TNE_anaphP_4059_2017/TPY_2017_4059 * 1000)
(iro_anaphN_4059_2017 <- TNE_anaphN_4059_2017/TPY_2017_4059 * 1000)
(iro_gbs_4059_2017 <- TNE_gbs_4059_2017/TPY_2017_4059 * 1000)
```

```{r}
#Events in 2017 for age group 00-19
events_2017_6079 <- subset(dftotal6079, year(end_incidence) == 2017) 
#the Total personyears for an event in 2017 age_band6079
TPY_2017_6079 <- sum(dftotal6079$years_in_study_2017)

# Count thenumber of events for age_band 6079 in 2017
TNE_anaphP_6079_2017 <- amount_events(events_2017_6079, 'anaphyl_possible')
TNE_anaphN_6079_2017 <- amount_events(events_2017_6079, 'anaphyl_narrow')
TNE_gbs_6079_2017 <- amount_events(events_2017_6079, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_6079_2017 <- TNE_anaphP_6079_2017/TPY_2017_6079 * 1000)
(iro_anaphN_6079_2017 <- TNE_anaphN_6079_2017/TPY_2017_6079 * 1000)
(iro_gbs_6079_2017 <- TNE_gbs_6079_2017/TPY_2017_6079 * 1000)
```

#2018 

```{r}
df_2018_0019 <- make_year_age_bands(df_2018, '[0,19]')
df_2018_2039 <- make_year_age_bands(df_2018, '[20,39]')
df_2018_4059 <- make_year_age_bands(df_2018, '[40,59]')
df_2018_6079 <- make_year_age_bands(df_2018, '[60,79]')
```


```{r}
events_2018_0019 <- subset(dftotal0019, year(end_incidence) == 2018) 

TPY_2018_0019 <- sum(df_2018_0019$years_in_study_2018)

# Count thenumber of events for age_band 0019 in 2018
TNE_anaphP_0019_2018 <- amount_events(events_2018_0019, 'anaphyl_possible')
TNE_anaphN_0019_2018 <- amount_events(events_2018_0019, 'anaphyl_narrow')
TNE_gbs_0019_2018 <- amount_events(events_2018_0019, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_0019_2018 <- TNE_anaphP_0019_2018/TPY_2018_0019 * 1000)
(iro_anaphN_0019_2018 <- TNE_anaphN_0019_2018/TPY_2018_0019 * 1000)
(iro_gbs_0019_2018 <- TNE_gbs_0019_2018/TPY_2018_0019 * 1000)
```

```{r}
events_2018_2039 <- subset(dftotal2039, year(end_incidence) == 2018) 

TPY_2018_2039 <- sum(df_2018_2039$years_in_study_2018)

# Count thenumber of events for age_band 2039 in 2018
TNE_anaphP_2039_2018 <- amount_events(events_2018_2039, 'anaphyl_possible')
TNE_anaphN_2039_2018 <- amount_events(events_2018_2039, 'anaphyl_narrow')
TNE_gbs_2039_2018 <- amount_events(events_2018_2039, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_2039_2018 <- TNE_anaphP_2039_2018/TPY_2018_2039 * 1000)
(iro_anaphN_2039_2018 <- TNE_anaphN_2039_2018/TPY_2018_2039 * 1000)
(iro_gbs_2039_2018 <- TNE_gbs_2039_2018/TPY_2018_2039 * 1000)
```

```{r}
events_2018_4059 <- subset(dftotal4059, year(end_incidence) == 2018) 

TPY_2018_4059 <- sum(df_2018_4059$years_in_study_2018)

# Count thenumber of events for age_band 4059 in 2018
TNE_anaphP_4059_2018 <- amount_events(events_2018_4059, 'anaphyl_possible')
TNE_anaphN_4059_2018 <- amount_events(events_2018_4059, 'anaphyl_narrow')
TNE_gbs_4059_2018 <- amount_events(events_2018_4059, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_4059_2018 <- TNE_anaphP_4059_2018/TPY_2018_4059 * 1000)
(iro_anaphN_4059_2018 <- TNE_anaphN_4059_2018/TPY_2018_4059 * 1000)
(iro_gbs_4059_2018 <- TNE_gbs_4059_2018/TPY_2018_4059 * 1000)
```

```{r}
events_2018_6079 <- subset(dftotal6079, year(end_incidence) == 2018) 

TPY_2018_6079 <- sum(df_2018_6079$years_in_study_2018)

# Count thenumber of events for age_band 6079 in 2018
TNE_anaphP_6079_2018 <- amount_events(events_2018_6079, 'anaphyl_possible')
TNE_anaphN_6079_2018 <- amount_events(events_2018_6079, 'anaphyl_narrow')
TNE_gbs_6079_2018 <- amount_events(events_2018_6079, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_6079_2018 <- TNE_anaphP_6079_2018/TPY_2018_6079 * 1000)
(iro_anaphN_6079_2018 <- TNE_anaphN_6079_2018/TPY_2018_6079 * 1000)
(iro_gbs_6079_2018 <- TNE_gbs_6079_2018/TPY_2018_6079 * 1000)
```

#2019 

```{r}
df_2019_0019 <- make_year_age_bands(df_2019, '[0,19]')
df_2019_2039 <- make_year_age_bands(df_2019, '[20,39]')
df_2019_4059 <- make_year_age_bands(df_2019, '[40,59]')
df_2019_6079 <- make_year_age_bands(df_2019, '[60,79]')
```


```{r}
events_2019_0019 <- subset(dftotal0019, year(end_incidence) == 2019) 

TPY_2019_0019 <- sum(df_2019_0019$years_in_study_2019)

# Count thenumber of events for age_band 0019 in 2019
TNE_anaphP_0019_2019 <- amount_events(events_2019_0019, 'anaphyl_possible')
TNE_anaphN_0019_2019 <- amount_events(events_2019_0019, 'anaphyl_narrow')
TNE_gbs_0019_2019 <- amount_events(events_2019_0019, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_0019_2019 <- TNE_anaphP_0019_2019/TPY_2019_0019 * 1000)
(iro_anaphN_0019_2019 <- TNE_anaphN_0019_2019/TPY_2019_0019 * 1000)
(iro_gbs_0019_2019 <- TNE_gbs_0019_2019/TPY_2019_0019 * 1000)
```

```{r}
events_2019_2039 <- subset(dftotal2039, year(end_incidence) == 2019) 

TPY_2019_2039 <- sum(df_2019_2039$years_in_study_2019)

# Count thenumber of events for age_band 2039 in 2019
TNE_anaphP_2039_2019 <- amount_events(events_2019_2039, 'anaphyl_possible')
TNE_anaphN_2039_2019 <- amount_events(events_2019_2039, 'anaphyl_narrow')
TNE_gbs_2039_2019 <- amount_events(events_2019_2039, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_2039_2019 <- TNE_anaphP_2039_2019/TPY_2019_2039 * 1000)
(iro_anaphN_2039_2019 <- TNE_anaphN_2039_2019/TPY_2019_2039 * 1000)
(iro_gbs_2039_2019 <- TNE_gbs_2039_2019/TPY_2019_2039 * 1000)
```

```{r}
events_2019_4059 <- subset(dftotal4059, year(end_incidence) == 2019) 

TPY_2019_4059 <- sum(df_2019_4059$years_in_study_2019)

# Count thenumber of events for age_band 4059 in 2019
TNE_anaphP_4059_2019 <- amount_events(events_2019_4059, 'anaphyl_possible')
TNE_anaphN_4059_2019 <- amount_events(events_2019_4059, 'anaphyl_narrow')
TNE_gbs_4059_2019 <- amount_events(events_2019_4059, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_4059_2019 <- TNE_anaphP_4059_2019/TPY_2019_4059 * 1000)
(iro_anaphN_4059_2019 <- TNE_anaphN_4059_2019/TPY_2019_4059 * 1000)
(iro_gbs_4059_2019 <- TNE_gbs_4059_2019/TPY_2019_4059 * 1000)
```

```{r}
events_2019_6079 <- subset(dftotal6079, year(end_incidence) == 2019) 

TPY_2019_6079 <- sum(df_2019_6079$years_in_study_2019)

# Count thenumber of events for age_band 6079 in 2019
TNE_anaphP_6079_2019 <- amount_events(events_2019_6079, 'anaphyl_possible')
TNE_anaphN_6079_2019 <- amount_events(events_2019_6079, 'anaphyl_narrow')
TNE_gbs_6079_2019 <- amount_events(events_2019_6079, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_6079_2019 <- TNE_anaphP_6079_2019/TPY_2019_6079 * 1000)
(iro_anaphN_6079_2019 <- TNE_anaphN_6079_2019/TPY_2019_6079 * 1000)
(iro_gbs_6079_2019 <- TNE_gbs_6079_2019/TPY_2019_6079 * 1000)
```

# 2020

2020 

```{r}
df_2020_0019 <- make_year_age_bands(df_2020, '[0,19]')
df_2020_2039 <- make_year_age_bands(df_2020, '[20,39]')
df_2020_4059 <- make_year_age_bands(df_2020, '[40,59]')
df_2020_6079 <- make_year_age_bands(df_2020, '[60,79]')
```


```{r}
events_2020_0019 <- subset(dftotal0019, year(end_incidence) == 2020) 

TPY_2020_0019 <- sum(df_2020_0019$years_in_study_2020)

# Count thenumber of events for age_band 0019 in 2020
TNE_anaphP_0019_2020 <- amount_events(events_2020_0019, 'anaphyl_possible')
TNE_anaphN_0019_2020 <- amount_events(events_2020_0019, 'anaphyl_narrow')
TNE_gbs_0019_2020 <- amount_events(events_2020_0019, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_0019_2020 <- TNE_anaphP_0019_2020/TPY_2020_0019 * 1000)
(iro_anaphN_0019_2020 <- TNE_anaphN_0019_2020/TPY_2020_0019 * 1000)
(iro_gbs_0019_2020 <- TNE_gbs_0019_2020/TPY_2020_0019 * 1000)
```

```{r}
events_2020_2039 <- subset(dftotal2039, year(end_incidence) == 2020) 

TPY_2020_2039 <- sum(df_2020_2039$years_in_study_2020)

# Count thenumber of events for age_band 2039 in 2020
TNE_anaphP_2039_2020 <- amount_events(events_2020_2039, 'anaphyl_possible')
TNE_anaphN_2039_2020 <- amount_events(events_2020_2039, 'anaphyl_narrow')
TNE_gbs_2039_2020 <- amount_events(events_2020_2039, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_2039_2020 <- TNE_anaphP_2039_2020/TPY_2020_2039 * 1000)
(iro_anaphN_2039_2020 <- TNE_anaphN_2039_2020/TPY_2020_2039 * 1000)
(iro_gbs_2039_2020 <- TNE_gbs_2039_2020/TPY_2020_2039 * 1000)
```

```{r}
events_2020_4059 <- subset(dftotal4059, year(end_incidence) == 2020) 

TPY_2020_4059 <- sum(df_2020_4059$years_in_study_2020)

# Count thenumber of events for age_band 4059 in 2020
TNE_anaphP_4059_2020 <- amount_events(events_2020_4059, 'anaphyl_possible')
TNE_anaphN_4059_2020 <- amount_events(events_2020_4059, 'anaphyl_narrow')
TNE_gbs_4059_2020 <- amount_events(events_2020_4059, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_4059_2020 <- TNE_anaphP_4059_2020/TPY_2020_4059 * 1000)
(iro_anaphN_4059_2020 <- TNE_anaphN_4059_2020/TPY_2020_4059 * 1000)
(iro_gbs_4059_2020 <- TNE_gbs_4059_2020/TPY_2020_4059 * 1000)
```

```{r}
events_2020_6079 <- subset(dftotal6079, year(end_incidence) == 2020) 

TPY_2020_6079 <- sum(df_2020_6079$years_in_study_2020)

# Count thenumber of events for age_band 6079 in 2020
TNE_anaphP_6079_2020 <- amount_events(events_2020_6079, 'anaphyl_possible')
TNE_anaphN_6079_2020 <- amount_events(events_2020_6079, 'anaphyl_narrow')
TNE_gbs_6079_2020 <- amount_events(events_2020_6079, 'gbs_narrow')

#IR for each event in 1000PY for age_band 0-19 
(iro_anaphP_6079_2020 <- TNE_anaphP_6079_2020/TPY_2020_6079 * 1000)
(iro_anaphN_6079_2020 <- TNE_anaphN_6079_2020/TPY_2020_6079 * 1000)
(iro_gbs_6079_2020 <- TNE_gbs_6079_2020/TPY_2020_6079 * 1000)
```

